channels:
  - conda-forge
dependencies:
  - aiohttp>=3.10.2
  - botocore
  - certifi
  - configobj
  - netifaces
  - pip
  - pip:
    - posttroll==1.15.0
    - pytroll-collectors==0.21.0
  - python=3.13
  - pyyaml
  - pyzmq
  - s3fs>=2026.4.0
  - trollsift=1.0.0
  - urllib3>=2.6.0
  - zeromq
  - zipp>=3.23.0
